import test,{before,after}from'node:test';import assert from'node:assert/strict';import request from'supertest';process.env.NODE_ENV='test';process.env.JWT_SECRET=process.env.JWT_SECRET||'integration-secret';const{default:app}=await import('../src/app.js');const{pool}=await import('../src/db.js');let departmentId,studentToken,studentId;async function cleanup(){const[[u]]=await pool.execute("SELECT s.student_id,u.user_id FROM students s JOIN users u ON u.user_id=s.user_id WHERE u.email='integration.student@example.edu'");if(!u)return;await pool.execute('DELETE FROM applications WHERE student_id=?',[u.student_id]);await pool.execute('DELETE FROM students WHERE student_id=?',[u.student_id]);await pool.execute('DELETE FROM users WHERE user_id=?',[u.user_id])}
before(async()=>{const[[d]]=await pool.query('SELECT department_id FROM departments LIMIT 1');departmentId=d.department_id;await cleanup()});
test('health reaches MySQL',async()=>{const r=await request(app).get('/api/health');assert.equal(r.status,200);assert.equal(r.body.status,'ok')});
test('registration validates and creates student transactionally',async()=>{const r=await request(app).post('/api/auth/register').send({email:'integration.student@example.edu',password:'StrongPass123!',registrationNo:'INTEGRATION001',departmentId,firstName:'Integration',graduationYear:2028});assert.equal(r.status,201)});
test('duplicate email/registration is rejected',async()=>{const r=await request(app).post('/api/auth/register').send({email:'integration.student@example.edu',password:'StrongPass123!',registrationNo:'INTEGRATION001',departmentId,firstName:'Integration',graduationYear:2028});assert.equal(r.status,409)});
test('invalid password rejected and valid login succeeds',async()=>{assert.equal((await request(app).post('/api/auth/login').send({email:'integration.student@example.edu',password:'wrong-password'})).status,401);const r=await request(app).post('/api/auth/login').send({email:'integration.student@example.edu',password:'StrongPass123!'});assert.equal(r.status,200);studentToken=r.body.token;const[[s]]=await pool.execute("SELECT s.student_id FROM students s JOIN users u ON u.user_id=s.user_id WHERE u.email='integration.student@example.edu'");studentId=s.student_id});
test('student cannot access admin routes',async()=>assert.equal((await request(app).get('/api/admin/applications').set('Authorization',`Bearer ${studentToken}`)).status,403));
test('internship list supports pagination and invalid id validation',async()=>{const r=await request(app).get('/api/internships?page=1&limit=2');assert.equal(r.status,200);assert.ok(Array.isArray(r.body.data));assert.equal((await request(app).get('/api/internships/not-a-number')).status,400)});
test('unique application constraint is enforced through API',async()=>{const[[i]]=await pool.query("SELECT internship_id FROM internships WHERE status='active' AND application_deadline>NOW() LIMIT 1");assert.ok(i,'demo seed must contain active internship');await pool.execute('UPDATE students SET cgpa=10 WHERE student_id=?',[studentId]);assert.equal((await request(app).post(`/api/student/internships/${i.internship_id}/apply`).set('Authorization',`Bearer ${studentToken}`).send({})).status,201);assert.equal((await request(app).post(`/api/student/internships/${i.internship_id}/apply`).set('Authorization',`Bearer ${studentToken}`).send({})).status,409)});
test('closed internship trigger rejects application when fixture exists',async()=>{const[[i]]=await pool.query("SELECT internship_id FROM internships WHERE status IN('closed','cancelled') OR application_deadline<=NOW() LIMIT 1");if(!i)return;assert.equal((await request(app).post(`/api/student/internships/${i.internship_id}/apply`).set('Authorization',`Bearer ${studentToken}`).send({})).status,409)});
after(async()=>{await cleanup();await pool.end()});
