import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import {pool} from './db.js';

const app=express(); app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173'})); app.use(express.json({limit:'1mb'}));
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const auth=(roles=[])=>wrap(async(req,res,next)=>{const token=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!token)return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(token,process.env.JWT_SECRET);if(roles.length&&!roles.includes(req.user.role))return res.status(403).json({error:'Forbidden'});next();}catch{return res.status(401).json({error:'Invalid or expired token'});}});
const studentId=async userId=>(await pool.execute('SELECT student_id FROM students WHERE user_id=?',[userId]))[0][0]?.student_id;

app.get('/api/health',wrap(async(_q,r)=>{await pool.query('SELECT 1');r.json({status:'ok',service:'campushire-api'});}));
app.post('/api/auth/register',wrap(async(q,r)=>{const {email,password,registrationNo,departmentId,firstName,lastName,graduationYear}=q.body;if(!email||!password||password.length<8||!registrationNo||!departmentId||!firstName||!graduationYear)return r.status(400).json({error:'Valid email, password (8+ chars), registration number, department, name and graduation year are required'});const c=await pool.getConnection();try{await c.beginTransaction();const hash=await bcrypt.hash(password,12);const [u]=await c.execute("INSERT INTO users(email,password_hash,role) VALUES(?,?,'student')",[email.toLowerCase(),hash]);await c.execute('INSERT INTO students(user_id,registration_no,department_id,first_name,last_name,graduation_year) VALUES(?,?,?,?,?,?)',[u.insertId,registrationNo,departmentId,firstName,lastName||null,graduationYear]);await c.commit();r.status(201).json({message:'Registered'});}catch(e){await c.rollback();if(e.code==='ER_DUP_ENTRY')return r.status(409).json({error:'Email or registration number already exists'});throw e;}finally{c.release();}}));
app.post('/api/auth/login',wrap(async(q,r)=>{const [rows]=await pool.execute('SELECT user_id,email,password_hash,role,is_active FROM users WHERE email=?',[String(q.body.email||'').toLowerCase()]);const u=rows[0];if(!u||!u.is_active||!(await bcrypt.compare(q.body.password||'',u.password_hash)))return r.status(401).json({error:'Invalid credentials'});r.json({token:jwt.sign({id:u.user_id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'8h'}),user:{id:u.user_id,email:u.email,role:u.role}});}));
app.get('/api/auth/me',auth(),(q,r)=>r.json({user:q.user}));
app.get('/api/meta',wrap(async(_q,r)=>{const [departments]=await pool.query('SELECT * FROM departments ORDER BY name');const [skills]=await pool.query('SELECT * FROM skills ORDER BY name');r.json({departments,skills});}));

app.get('/api/internships',wrap(async(q,r)=>{const page=Math.max(1,+q.query.page||1),limit=Math.min(50,Math.max(1,+q.query.limit||12)),off=(page-1)*limit,w=["i.status='active'","i.application_deadline>NOW()"],p=[];for(const [key,col] of [['location','i.location'],['mode','i.work_mode']])if(q.query[key]){w.push(`${col}=?`);p.push(q.query[key]);}if(q.query.company){w.push('c.name LIKE ?');p.push(`%${q.query.company}%`)}if(q.query.minStipend){w.push('i.stipend>=?');p.push(+q.query.minStipend)}if(q.query.q){w.push('(i.title LIKE ? OR i.description LIKE ? OR c.name LIKE ?)');p.push(...Array(3).fill(`%${q.query.q}%`))}if(q.query.skill){w.push('EXISTS(SELECT 1 FROM internship_skills x JOIN skills sk ON sk.skill_id=x.skill_id WHERE x.internship_id=i.internship_id AND sk.name=?)');p.push(q.query.skill)}const where=w.join(' AND ');const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM internships i JOIN companies c ON c.company_id=i.company_id WHERE ${where}`,p);const [data]=await pool.execute(`SELECT i.*,c.name company,ind.name industry FROM internships i JOIN companies c ON c.company_id=i.company_id JOIN industries ind ON ind.industry_id=c.industry_id WHERE ${where} ORDER BY i.application_deadline LIMIT ? OFFSET ?`,[...p,limit,off]);r.json({data,page,limit,total:count.total,pages:Math.ceil(count.total/limit)});}));
app.get('/api/internships/:id',wrap(async(q,r)=>{const [rows]=await pool.execute('SELECT i.*,c.name company,c.website,ind.name industry FROM internships i JOIN companies c ON c.company_id=i.company_id JOIN industries ind ON ind.industry_id=c.industry_id WHERE i.internship_id=?',[q.params.id]);if(!rows[0])return r.status(404).json({error:'Not found'});const [skills]=await pool.execute('SELECT s.skill_id,s.name,x.is_required FROM internship_skills x JOIN skills s ON s.skill_id=x.skill_id WHERE x.internship_id=?',[q.params.id]);r.json({...rows[0],skills});}));

app.get('/api/student/profile',auth(['student']),wrap(async(q,r)=>{const [x]=await pool.execute('SELECT s.*,d.code department_code,d.name department,u.email FROM students s JOIN departments d ON d.department_id=s.department_id JOIN users u ON u.user_id=s.user_id WHERE s.user_id=?',[q.user.id]);if(!x[0])return r.status(404).json({error:'Profile not found'});const [skills]=await pool.execute('SELECT sk.*,ss.proficiency FROM student_skills ss JOIN skills sk ON sk.skill_id=ss.skill_id WHERE ss.student_id=?',[x[0].student_id]);r.json({...x[0],skills});}));
app.put('/api/student/profile',auth(['student']),wrap(async(q,r)=>{const {firstName,lastName,phone,cgpa,resumeUrl,bio}=q.body;await pool.execute('UPDATE students SET first_name=COALESCE(?,first_name),last_name=?,phone=?,cgpa=?,resume_url=?,bio=? WHERE user_id=?',[firstName||null,lastName||null,phone||null,cgpa??null,resumeUrl||null,bio||null,q.user.id]);r.json({message:'Profile updated'});}));
app.put('/api/student/skills',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id),skills=Array.isArray(q.body.skills)?q.body.skills:[];const c=await pool.getConnection();try{await c.beginTransaction();await c.execute('DELETE FROM student_skills WHERE student_id=?',[sid]);for(const x of skills)await c.execute('INSERT INTO student_skills(student_id,skill_id,proficiency) VALUES(?,?,?)',[sid,x.skillId,x.proficiency||'intermediate']);await c.commit();r.json({message:'Skills updated'});}catch(e){await c.rollback();throw e;}finally{c.release();}}));
app.post('/api/internships/:id/apply',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);try{const [a]=await pool.execute('INSERT INTO applications(student_id,internship_id,cover_letter) VALUES(?,?,?)',[sid,q.params.id,q.body.coverLetter||null]);r.status(201).json({applicationId:a.insertId});}catch(e){if(e.code==='ER_DUP_ENTRY')return r.status(409).json({error:'You already applied'});if(e.sqlState==='45000')return r.status(409).json({error:e.sqlMessage});throw e;}}));
app.get('/api/student/dashboard',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);const [[counts]]=await pool.execute("SELECT COUNT(*) applications,SUM(status='shortlisted') shortlisted,SUM(status='offered') offered FROM applications WHERE student_id=?",[sid]);const [upcoming]=await pool.execute("SELECT iv.*,i.title,c.name company FROM interviews iv JOIN applications a ON a.application_id=iv.application_id JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id WHERE a.student_id=? AND iv.scheduled_at>=NOW() ORDER BY iv.scheduled_at LIMIT 5",[sid]);r.json({counts,upcoming});}));
app.get('/api/applications/me',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);const [x]=await pool.execute('SELECT a.*,i.title,c.name company FROM applications a JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id WHERE a.student_id=? ORDER BY a.applied_at DESC',[sid]);r.json(x);}));
app.get('/api/interviews/me',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);const [x]=await pool.execute('SELECT iv.*,i.title,c.name company FROM interviews iv JOIN applications a ON a.application_id=iv.application_id JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id WHERE a.student_id=? ORDER BY iv.scheduled_at DESC',[sid]);r.json(x);}));
app.get('/api/offers/me',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);const [x]=await pool.execute('SELECT o.*,i.title,c.name company FROM offers o JOIN applications a ON a.application_id=o.application_id JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id WHERE a.student_id=? ORDER BY o.offered_at DESC',[sid]);r.json(x);}));
app.patch('/api/offers/:id/respond',auth(['student']),wrap(async(q,r)=>{if(!['accepted','rejected'].includes(q.body.status))return r.status(400).json({error:'Status must be accepted or rejected'});const sid=await studentId(q.user.id);const [x]=await pool.execute("UPDATE offers o JOIN applications a ON a.application_id=o.application_id SET o.status=?,o.responded_at=NOW() WHERE o.offer_id=? AND a.student_id=? AND o.status='pending'",[q.body.status,q.params.id,sid]);if(!x.affectedRows)return r.status(404).json({error:'Pending offer not found'});r.json({message:'Offer response recorded'});}));
app.get('/api/records/me',auth(['student']),wrap(async(q,r)=>{const sid=await studentId(q.user.id);const [x]=await pool.execute('SELECT rec.*,i.title,c.name company,e.score,e.feedback FROM internship_records rec JOIN offers o ON o.offer_id=rec.offer_id JOIN applications a ON a.application_id=o.application_id JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id LEFT JOIN evaluations e ON e.record_id=rec.record_id WHERE a.student_id=? ORDER BY rec.start_date DESC',[sid]);r.json(x);}));

app.get('/api/admin/:resource(students|companies|internships|applications|interviews|offers|records|evaluations)',auth(['admin']),wrap(async(q,r)=>{const map={students:'students',companies:'companies',internships:'internships',applications:'applications',interviews:'interviews',offers:'offers',records:'internship_records',evaluations:'evaluations'};const [x]=await pool.query(`SELECT * FROM ${map[q.params.resource]} ORDER BY 1 DESC LIMIT 500`);r.json(x);}));
app.post('/api/admin/companies',auth(['admin']),wrap(async(q,r)=>{const {industryId,name,website,location,description}=q.body;const [x]=await pool.execute('INSERT INTO companies(industry_id,name,website,location,description) VALUES(?,?,?,?,?)',[industryId,name,website||null,location||null,description||null]);r.status(201).json({companyId:x.insertId});}));
app.post('/api/admin/internships',auth(['admin']),wrap(async(q,r)=>{const x=q.body;const [v]=await pool.execute('INSERT INTO internships(company_id,title,description,location,work_mode,stipend,duration_weeks,openings,minimum_cgpa,application_deadline,start_date,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[x.companyId,x.title,x.description,x.location,x.workMode,x.stipend||0,x.durationWeeks,x.openings||1,x.minimumCgpa||null,x.applicationDeadline,x.startDate||null,x.status||'active']);r.status(201).json({internshipId:v.insertId});}));
app.patch('/api/admin/applications/:id/status',auth(['admin']),wrap(async(q,r)=>{const allowed=['submitted','under_review','shortlisted','interview','rejected','offered','withdrawn'];if(!allowed.includes(q.body.status))return r.status(400).json({error:'Invalid status'});await pool.execute('UPDATE applications SET status=? WHERE application_id=?',[q.body.status,q.params.id]);r.json({message:'Application updated'});}));
app.post('/api/admin/interviews',auth(['admin']),wrap(async(q,r)=>{const x=q.body;const [v]=await pool.execute('INSERT INTO interviews(application_id,round_no,scheduled_at,mode,meeting_link,venue,notes) VALUES(?,?,?,?,?,?,?)',[x.applicationId,x.roundNo||1,x.scheduledAt,x.mode,x.meetingLink||null,x.venue||null,x.notes||null]);await pool.execute("UPDATE applications SET status='interview' WHERE application_id=?",[x.applicationId]);r.status(201).json({interviewId:v.insertId});}));
app.patch('/api/admin/interviews/:id/result',auth(['admin']),wrap(async(q,r)=>{if(!['pending','passed','failed','no_show'].includes(q.body.result))return r.status(400).json({error:'Invalid result'});await pool.execute('UPDATE interviews SET result=?,notes=COALESCE(?,notes) WHERE interview_id=?',[q.body.result,q.body.notes||null,q.params.id]);r.json({message:'Interview updated'});}));
app.post('/api/admin/offers',auth(['admin']),wrap(async(q,r)=>{const x=q.body;try{const [v]=await pool.execute('INSERT INTO offers(application_id,response_deadline,stipend) VALUES(?,?,?)',[x.applicationId,x.responseDeadline,x.stipend]);await pool.execute("UPDATE applications SET status='offered' WHERE application_id=?",[x.applicationId]);r.status(201).json({offerId:v.insertId});}catch(e){if(e.sqlState==='45000')return r.status(409).json({error:e.sqlMessage});throw e;}}));
app.post('/api/admin/records',auth(['admin']),wrap(async(q,r)=>{const x=q.body;try{const [v]=await pool.execute('INSERT INTO internship_records(offer_id,start_date,end_date,status,completion_notes) VALUES(?,?,?,?,?)',[x.offerId,x.startDate,x.endDate||null,x.status||'upcoming',x.completionNotes||null]);r.status(201).json({recordId:v.insertId});}catch(e){if(e.sqlState==='45000')return r.status(409).json({error:e.sqlMessage});throw e;}}));
app.patch('/api/admin/records/:id',auth(['admin']),wrap(async(q,r)=>{await pool.execute('UPDATE internship_records SET status=?,end_date=COALESCE(?,end_date),completion_notes=COALESCE(?,completion_notes) WHERE record_id=?',[q.body.status,q.body.endDate||null,q.body.completionNotes||null,q.params.id]);r.json({message:'Record updated'});}));
app.post('/api/admin/evaluations',auth(['admin']),wrap(async(q,r)=>{try{const [v]=await pool.execute('INSERT INTO evaluations(record_id,score,feedback) VALUES(?,?,?)',[q.body.recordId,q.body.score,q.body.feedback||null]);r.status(201).json({evaluationId:v.insertId});}catch(e){if(e.sqlState==='45000')return r.status(409).json({error:e.sqlMessage});throw e;}}));
app.get('/api/admin/analytics',auth(['admin']),wrap(async(_q,r)=>{const [[totals]]=await pool.query('SELECT (SELECT COUNT(*) FROM students) students,(SELECT COUNT(*) FROM companies) companies,(SELECT COUNT(*) FROM internships) internships,(SELECT COUNT(*) FROM applications) applications,(SELECT COUNT(*) FROM offers) offers');const [skills]=await pool.query('SELECT sk.name,COUNT(*) demand FROM skills sk JOIN internship_skills x ON x.skill_id=sk.skill_id GROUP BY sk.skill_id,sk.name ORDER BY demand DESC LIMIT 10');const [departments]=await pool.query('SELECT * FROM placement_statistics ORDER BY applications DESC');const [companies]=await pool.query('SELECT * FROM company_recruitment_summary ORDER BY applications DESC LIMIT 10');r.json({totals,skills,departments,companies});}));

app.use((_q,r)=>r.status(404).json({error:'Route not found'}));app.use((e,_q,r,_n)=>{console.error(e);if(e.code==='ER_DUP_ENTRY')return r.status(409).json({error:'Duplicate record'});if(e.code?.startsWith('ER_NO_REFERENCED'))return r.status(422).json({error:'Referenced record does not exist'});r.status(500).json({error:'Internal server error'});});
export default app;
