import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import mysql from 'mysql2/promise';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';

export const pool=mysql.createPool({host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'campushire',password:process.env.DB_PASSWORD||'campushire',database:process.env.DB_NAME||'campushire',waitForConnections:true,connectionLimit:10});
const app=express();
app.use(helmet()); app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173'})); app.use(express.json());
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const auth=(roles=[])=>asyncRoute(async(req,res,next)=>{const h=req.headers.authorization;if(!h?.startsWith('Bearer ')) return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET);if(roles.length&&!roles.includes(req.user.role))return res.status(403).json({error:'Forbidden'});next();}catch{return res.status(401).json({error:'Invalid token'});}});

app.get('/api/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({status:'ok'});}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const {email,password,registrationNo,departmentId,firstName,lastName,graduationYear}=req.body;if(!email||!password||!registrationNo||!departmentId||!firstName||!graduationYear)return res.status(400).json({error:'Missing required fields'});const conn=await pool.getConnection();try{await conn.beginTransaction();const hash=await bcrypt.hash(password,12);const [u]=await conn.execute("INSERT INTO users(email,password_hash,role) VALUES(?,?,'student')",[email,hash]);await conn.execute('INSERT INTO students(user_id,registration_no,department_id,first_name,last_name,graduation_year) VALUES(?,?,?,?,?,?)',[u.insertId,registrationNo,departmentId,firstName,lastName||null,graduationYear]);await conn.commit();res.status(201).json({message:'Registered'});}catch(e){await conn.rollback();if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'Email or registration number already exists'});throw e;}finally{conn.release();}}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const [rows]=await pool.execute('SELECT user_id,email,password_hash,role,is_active FROM users WHERE email=?',[req.body.email]);const u=rows[0];if(!u||!u.is_active||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:u.user_id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'8h'});res.json({token,user:{id:u.user_id,email:u.email,role:u.role}});}));
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:req.user}));

app.get('/api/internships',asyncRoute(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)),offset=(page-1)*limit;const where=["i.status='active'","i.application_deadline>NOW()"],p=[];if(req.query.location){where.push('i.location LIKE ?');p.push(`%${req.query.location}%`);}if(req.query.mode){where.push('i.work_mode=?');p.push(req.query.mode);}if(req.query.company){where.push('c.name LIKE ?');p.push(`%${req.query.company}%`);}if(req.query.q){where.push('(i.title LIKE ? OR i.description LIKE ?)');p.push(`%${req.query.q}%`,`%${req.query.q}%`);}const [rows]=await pool.execute(`SELECT i.*,c.name company,ind.name industry FROM internships i JOIN companies c ON c.company_id=i.company_id JOIN industries ind ON ind.industry_id=c.industry_id WHERE ${where.join(' AND ')} ORDER BY i.application_deadline LIMIT ? OFFSET ?`,[...p,limit,offset]);res.json({page,limit,data:rows});}));
app.get('/api/internships/:id',asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT i.*,c.name company,ind.name industry FROM internships i JOIN companies c ON c.company_id=i.company_id JOIN industries ind ON ind.industry_id=c.industry_id WHERE i.internship_id=?',[req.params.id]);if(!r[0])return res.status(404).json({error:'Internship not found'});const [skills]=await pool.execute('SELECT s.skill_id,s.name,isk.is_required FROM internship_skills isk JOIN skills s ON s.skill_id=isk.skill_id WHERE isk.internship_id=?',[req.params.id]);res.json({...r[0],skills});}));
app.post('/api/internships/:id/apply',auth(['student']),asyncRoute(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [s]=await conn.execute('SELECT student_id,cgpa FROM students WHERE user_id=?',[req.user.id]);if(!s[0])return res.status(404).json({error:'Student profile missing'});const [i]=await conn.execute('SELECT internship_id,status,application_deadline,minimum_cgpa FROM internships WHERE internship_id=? FOR UPDATE',[req.params.id]);if(!i[0])return res.status(404).json({error:'Internship not found'});if(i[0].status!=='active'||new Date(i[0].application_deadline)<=new Date())return res.status(409).json({error:'Internship is closed'});if(i[0].minimum_cgpa!=null&&(s[0].cgpa==null||Number(s[0].cgpa)<Number(i[0].minimum_cgpa)))return res.status(422).json({error:'Minimum CGPA requirement not met'});const [a]=await conn.execute('INSERT INTO applications(student_id,internship_id,cover_letter) VALUES(?,?,?)',[s[0].student_id,req.params.id,req.body.coverLetter||null]);await conn.commit();res.status(201).json({applicationId:a.insertId});}catch(e){await conn.rollback();if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'Already applied'});throw e;}finally{conn.release();}}));
app.get('/api/applications/me',auth(['student']),asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT a.*,i.title,c.name company FROM students s JOIN applications a ON a.student_id=s.student_id JOIN internships i ON i.internship_id=a.internship_id JOIN companies c ON c.company_id=i.company_id WHERE s.user_id=? ORDER BY a.applied_at DESC',[req.user.id]);res.json(r);}));
app.get('/api/admin/analytics',auth(['admin']),asyncRoute(async(_req,res)=>{const [[students]]=await pool.query('SELECT COUNT(*) count FROM students');const [[internships]]=await pool.query('SELECT COUNT(*) count FROM internships');const [[applications]]=await pool.query('SELECT COUNT(*) count FROM applications');const [[offers]]=await pool.query('SELECT COUNT(*) count FROM offers');const [skills]=await pool.query('SELECT sk.name,COUNT(*) demand FROM skills sk JOIN internship_skills isk ON isk.skill_id=sk.skill_id GROUP BY sk.skill_id,sk.name ORDER BY demand DESC LIMIT 10');res.json({students:students.count,internships:internships.count,applications:applications.count,offers:offers.count,topSkills:skills});}));

app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
const port=Number(process.env.PORT||4000);if(process.env.NODE_ENV!=='test')app.listen(port,()=>console.log(`CampusHire API on :${port}`));
export default app;
