USE campushire;
DELIMITER $$
CREATE TRIGGER trg_application_before_insert BEFORE INSERT ON applications FOR EACH ROW BEGIN DECLARE v_status VARCHAR(20);DECLARE v_deadline DATETIME;DECLARE v_min DECIMAL(4,2);DECLARE v_cgpa DECIMAL(4,2);IF COALESCE(@campushire_bulk_seed,0)=0 THEN SELECT status,application_deadline,minimum_cgpa INTO v_status,v_deadline,v_min FROM internships WHERE internship_id=NEW.internship_id;SELECT cgpa INTO v_cgpa FROM students WHERE student_id=NEW.student_id;IF v_status IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Internship does not exist';END IF;IF v_status<>'active' OR v_deadline<=NOW() THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Applications are closed for this internship';END IF;IF v_min IS NOT NULL AND(v_cgpa IS NULL OR v_cgpa<v_min) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Minimum CGPA requirement not met';END IF;END IF;END$$
CREATE TRIGGER trg_application_after_insert AFTER INSERT ON applications FOR EACH ROW BEGIN IF COALESCE(@campushire_bulk_seed,0)=0 THEN INSERT INTO application_status_history(application_id,old_status,new_status,changed_by,reason) VALUES(NEW.application_id,NULL,NEW.status,NULL,'Application submitted');END IF;END$$
CREATE TRIGGER trg_application_after_update AFTER UPDATE ON applications FOR EACH ROW BEGIN IF COALESCE(@campushire_bulk_seed,0)=0 AND OLD.status<>NEW.status THEN INSERT INTO application_status_history(application_id,old_status,new_status,changed_by,reason) VALUES(NEW.application_id,OLD.status,NEW.status,@actor_user_id,@status_reason);END IF;END$$
CREATE TRIGGER trg_interview_before_insert BEFORE INSERT ON interviews FOR EACH ROW BEGIN DECLARE v_applied DATETIME;IF COALESCE(@campushire_bulk_seed,0)=0 THEN SELECT applied_at INTO v_applied FROM applications WHERE application_id=NEW.application_id;IF v_applied IS NULL OR NEW.scheduled_at<=v_applied THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Interview must occur after application';END IF;END IF;END$$
CREATE TRIGGER trg_offer_before_insert BEFORE INSERT ON offers FOR EACH ROW BEGIN DECLARE v_status VARCHAR(20);IF COALESCE(@campushire_bulk_seed,0)=0 THEN SELECT status INTO v_status FROM applications WHERE application_id=NEW.application_id;IF v_status NOT IN('shortlisted','interview','offered') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offer requires an eligible application stage';END IF;END IF;END$$
CREATE TRIGGER trg_record_before_insert BEFORE INSERT ON internship_records FOR EACH ROW BEGIN DECLARE v_status VARCHAR(20);DECLARE v_responded DATETIME;IF COALESCE(@campushire_bulk_seed,0)=0 THEN SELECT status,responded_at INTO v_status,v_responded FROM offers WHERE offer_id=NEW.offer_id;IF v_status<>'accepted' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Internship record requires accepted offer';END IF;IF v_responded IS NOT NULL AND NEW.start_date<DATE(v_responded) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Internship cannot begin before offer acceptance';END IF;END IF;END$$
CREATE TRIGGER trg_evaluation_before_insert BEFORE INSERT ON evaluations FOR EACH ROW BEGIN DECLARE v_status VARCHAR(20);DECLARE v_end DATE;IF COALESCE(@campushire_bulk_seed,0)=0 THEN SELECT status,end_date INTO v_status,v_end FROM internship_records WHERE record_id=NEW.record_id;IF v_status<>'completed' OR v_end IS NULL OR DATE(NEW.evaluated_at)<v_end THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Evaluation requires a completed internship';END IF;END IF;END$$
DELIMITER ;
